version: "3.1"
services:
  backend:
    image: nicolausc/impensa-be-dev:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=PROD
    secrets:
      - IMPENSA_BE_API_SECRET
      - IMPENSA_BE_MGOCONNSTRING
      - IMPENSA_BE_MAILGUN_API
      - IMPENSA_BE_GOOGLE_OAUTH_CLIENT_ID
      - IMPENSA_BE_GOOGLE_OAUTH_CLIENT_SECRET
    volumes:
      - ./.env:/app/.env

  frontend:
    image: nicolausc/impensa-fe-dev:latest
    restart: always
    ports:
      - "3000:80"
    environment: :
      - VIRTUAL_HOST=impensa.nicolauscg.com
      - LETSENCRYPT_HOST=impensa.nicolauscg.com
      - VIRTUAL_PORT=3000

secrets:
  IMPENSA_BE_API_SECRET:
    file: impensa_be_api_secret.txt
  IMPENSA_BE_MGOCONNSTRING:
    file: impensa_be_mgoconnstring.txt
  IMPENSA_BE_MAILGUN_API:
    file: impensa_be_mailgun_api.txt
  IMPENSA_BE_GOOGLE_OAUTH_CLIENT_ID:
    file: impensa_be_google_oauth_client_id.txt
  IMPENSA_BE_GOOGLE_OAUTH_CLIENT_SECRET:
    file: impensa_be_google_oauth_client_secret.txt
