version: "3.1"
services:
  backend:
    image: nicolausc/impensa-be-dev:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=PROD
    secrets:
      - IMPENSA_BE_API_SECRET
      - IMPENSA_BE_MGOCONNSTRING
    volumes:
      - ./.env:/app/.env

  frontend:
    image: nicolausc/impensa-fe-dev:latest
    restart: always
    ports:
      - "3000:80"
  
  nginx:
    image: nginx:1.17-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d

secrets:
  IMPENSA_BE_API_SECRET:
    file: impensa_be_api_secret.txt
  IMPENSA_BE_MGOCONNSTRING:
    file: impensa_be_mgoconnstring.txt
